# Generated by Django 4.1.5 on 2023-01-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='addedat',
            field=models.CharField(default='String', max_length=100),
        ),
    ]
